### PR TITLE
Vervecard support

### PR DESCRIPTION
**Pull request by nwaughachukwuma**
Hi @ebellumat, with reference to this [issue](https://github.com/sbycrosz/react-native-credit-card-input/pull/156), I have made a new PR. Do let me know what you think

### CODE REVIEW

**Comment by ebellumat** [comment]
@nwaughachukwuma Done! Thanks! Soon i will release this on NPM

**Comment by Noitidart** [comment]
Is this repo the new place for supporte version of react-native-credit-card-input? because i have a pr ready

**Comment by nwaughachukwuma** [comment]
Yes it is. Please feel welcome to submit your PR

**Comment by Noitidart** [comment]
Thank you!

**Pull request merged**
